--liquibase formatted sql

--changeset osipova.va:role failOnError:True dbms:postgresql

create table if not exists role
(
    id bigint generated by default as identity
        constraint role_pkey
            primary key,
    name varchar(15) not null
);

alter table post owner to postgres;