--liquibase formatted sql

--changeset osipova.va:users, role, user_roles, insert failOnError:True dbms:postgresql

create table if not exists users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    name varchar(15) not null,
    first_name varchar(15) not null,
    last_name varchar(15) not null,
    email varchar(50) not null,
    password varchar(255) not null,
    rating integer
);

alter table users owner to postgres;

create table if not exists role
(
    id bigint generated by default as identity
        constraint role_pkey
            primary key,
    name varchar(15) not null
);

alter table role owner to postgres;

create table user_roles(
      user_id int not null ,
      role_id int not null ,
      foreign key (user_id) references users(id),
      foreign key (role_id) references role(id),

       unique (user_id, role_id)

);
alter table user_roles owner to postgres;

--insert data
insert into users values (1,
                          'Виктория',
                          'Александровна',
                          'Осипова',
                          'yan-vichka@mail.ru',
                          '$2a$11$uSXS6rLJ91WjgOHhEGDx..VGs7MkKZV68Lv5r1uwFu7HgtRn3dcXG');
insert into role values (1, 'ROLE_USER');
insert into role values (2, 'ROLE_ADMIN');
insert into role values (3, 'ROLE_WRITER');
insert into user_roles values (1, 2);
