--liquibase formatted sql

--changeset osipova.va:init failOnError:True dbms:postgresql

create table if not exists post
(
    id bigint generated by default as identity
        constraint post_pkey
            primary key,
    title varchar(50) not null,
    anons varchar(50) not null,
    full_text varchar(1000) not null,
    views bigint
);

alter table post owner to postgres;

