--liquibase formatted sql

--changeset osipova.va:user failOnError:True dbms:postgresql

create table if not exists users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    name varchar(15) not null,
    first_name varchar(15) not null,
    last_name varchar(15) not null,
    email varchar(50) not null,
    password varchar(10) not null,
    roles varchar(10) not null,
    rating integer
);

alter table post owner to postgres;